version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout
      - run:
          name: test
          command: ./gradlew test
      - run:
          name: build
          command: ./gradlew build
