version: 2.1
orbs:
  android: circleci/android@0.2.1
jobs:
  build:
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew test
      - run:
          name: Build
          command: ./gradlew build
